services:
  db:
    image: mysql:8.0.33
    container_name: mysql
    environment:
      MYSQL_DATABASE: nunesSportDB
      MYSQL_ROOT_PASSWORD: rootPassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - nunes-sport-network

networks:
  nunes-sport-network:
    driver: bridge

volumes:
  db: