
networks:
  nunes-sport:
    driver: bridge
    name: nunes-sport

volumes:
  mysqlDB:
    name: mysql

services:
  mysql:
    image: mysql:8.0.31
    container_name: mysql01
    environment:
      MYSQL_DATABASE: nunes_sport
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysqlDB:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - nunes-sport


  nunes_sport:
    build: .
    container_name: nunes_sport01
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/nunes_sport
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    networks:
      - nunes-sport-network



